#!/bin/bash
# Laravel Bulk Installer - Apache Configuration Script
# Configures Homebrew Apache httpd for Laravel development.
#
# Usage: ./configure-apache.sh

set -e

echo "=== Laravel Bulk Installer - Apache Configuration ==="
echo ""

# Detect architecture
ARCH=$(uname -m)
if [ "$ARCH" = "arm64" ]; then
    HOMEBREW_PREFIX="/opt/homebrew"
else
    HOMEBREW_PREFIX="/usr/local"
fi

echo "Architecture: $ARCH"
echo "Homebrew prefix: $HOMEBREW_PREFIX"
echo ""

HTTPD_CONF="$HOMEBREW_PREFIX/etc/httpd/httpd.conf"
SITES_AVAILABLE="$HOMEBREW_PREFIX/etc/httpd/sites-available"
SITES_ENABLED="$HOMEBREW_PREFIX/etc/httpd/sites-enabled"
LOG_DIR="$HOMEBREW_PREFIX/var/log/httpd"
WWW_ROOT="$HOMEBREW_PREFIX/var/www"
WWW_HTML="$HOMEBREW_PREFIX/var/www/html"

# Check if httpd is installed
if [ ! -f "$HTTPD_CONF" ]; then
    echo "Apache httpd not found. Installing via Homebrew..."
    brew install httpd
fi

echo "[1/6] Creating directory structure..."

sudo mkdir -p "$SITES_AVAILABLE"
sudo mkdir -p "$SITES_ENABLED"
sudo mkdir -p "$LOG_DIR"
sudo mkdir -p "$WWW_ROOT"
sudo mkdir -p "$WWW_HTML"

# Set ownership
sudo chown -R "$(whoami):staff" "$WWW_ROOT"
sudo chmod -R 775 "$WWW_ROOT"

echo "    Directories created"

echo "[2/6] Backing up httpd.conf..."

BACKUP_FILE="${HTTPD_CONF}.backup.$(date +%Y%m%d%H%M%S)"
sudo cp "$HTTPD_CONF" "$BACKUP_FILE"
echo "    Backed up to: $BACKUP_FILE"

echo "[3/6] Enabling required modules..."

# Modules to enable
MODULES=(
    "rewrite_module"
    "proxy_module"
    "proxy_fcgi_module"
    "vhost_alias_module"
    "headers_module"
)

for mod in "${MODULES[@]}"; do
    if grep -q "#LoadModule $mod" "$HTTPD_CONF"; then
        sudo sed -i.bak "s/#LoadModule $mod/LoadModule $mod/" "$HTTPD_CONF"
        echo "    Enabled: $mod"
    elif grep -q "LoadModule $mod" "$HTTPD_CONF"; then
        echo "    Already enabled: $mod"
    else
        echo "    Not found: $mod"
    fi
done

echo "[4/6] Configuring sites-enabled include..."

if ! grep -q "sites-enabled" "$HTTPD_CONF"; then
    echo "" | sudo tee -a "$HTTPD_CONF" > /dev/null
    echo "# Laravel Bulk Installer - VirtualHost configurations" | sudo tee -a "$HTTPD_CONF" > /dev/null
    echo "IncludeOptional $SITES_ENABLED/*.conf" | sudo tee -a "$HTTPD_CONF" > /dev/null
    echo "    Added sites-enabled include"
else
    echo "    Sites-enabled include already configured"
fi

echo "[5/6] Configuring PHP-FPM handler..."

# Create a default PHP-FPM configuration
PHP_CONF="$SITES_AVAILABLE/00-php-fpm.conf"

# Find installed PHP version
PHP_VERSION=""
for dir in "$HOMEBREW_PREFIX/opt/php@"*; do
    if [ -d "$dir" ]; then
        PHP_VERSION=$(basename "$dir" | sed 's/php@//')
        break
    fi
done

if [ -z "$PHP_VERSION" ]; then
    if [ -d "$HOMEBREW_PREFIX/opt/php" ]; then
        PHP_VERSION=$("$HOMEBREW_PREFIX/opt/php/bin/php" -v | head -1 | grep -oE '[0-9]+\.[0-9]+' | head -1)
    fi
fi

if [ -n "$PHP_VERSION" ]; then
    PHP_FPM_SOCK="$HOMEBREW_PREFIX/var/run/php@${PHP_VERSION}-fpm.sock"

    cat << EOF | sudo tee "$PHP_CONF" > /dev/null
# PHP-FPM Configuration for Laravel
# Auto-generated by configure-apache.sh

<FilesMatch \.php$>
    SetHandler "proxy:unix:${PHP_FPM_SOCK}|fcgi://localhost/"
</FilesMatch>

<Directory "$WWW_HTML">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
EOF

    # Enable PHP config
    sudo ln -sf "$PHP_CONF" "$SITES_ENABLED/00-php-fpm.conf"
    echo "    PHP-FPM handler configured for PHP $PHP_VERSION"
else
    echo "    WARNING: PHP not found, skipping PHP-FPM configuration"
fi

echo "[6/6] Testing configuration..."

if "$HOMEBREW_PREFIX/bin/apachectl" configtest 2>&1 | grep -q "Syntax OK"; then
    echo "    Configuration syntax OK"
else
    echo "    WARNING: Configuration test failed. Check $HTTPD_CONF"
fi

echo ""
echo "=== Configuration Complete ==="
echo ""
echo "To start Apache, run:"
echo "  brew services start httpd"
echo ""
echo "To start PHP-FPM, run:"
echo "  brew services start php"
echo ""
echo "Configuration files:"
echo "  Apache config: $HTTPD_CONF"
echo "  Sites available: $SITES_AVAILABLE/"
echo "  Sites enabled: $SITES_ENABLED/"
echo "  Web root: $WWW_ROOT/"
echo ""
